name: pewpew_connect # Dieses Feld muss an erster Stelle stehen
description: Eine Airsoft App mit Login und Firebase
publish_to: 'none' # weil lokal
version: 2.6.8

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  firebase_remote_config: ^6.0.0
  flutter_local_notifications: ^17.0.0
  
  # NEU: FÃ¼r HTTP-Anfragen an den Server
  http: ^1.2.1

  # State Management / Utils
  provider: ^6.1.1

  # Standard Flutter Icons
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0
  lehttp_overrides: ^1.0.3
  shared_preferences: ^2.5.4
  permission_handler: ^11.3.1
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  geolocator: ^9.0.2
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/ppc.jpg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/ppc.jpg
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_bgr.jpg
    - assets/images/app_bgr2.jpg
    - assets/images/ppc.jpg