name: pewpew_connect # Dieses Feld muss an erster Stelle stehen
description: Eine Airsoft App mit Login und Firebase
publish_to: 'none' # weil lokal
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  
  # NEU: FÃ¼r HTTP-Anfragen an den Server
  http: ^1.2.1

  # State Management / Utils
  provider: ^6.0.1

  # Standard Flutter Icons
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0
  lehttp_overrides: ^1.0.3
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_bgr.jpg
    - assets/images/app_bgr2.jpg